[package]
name = "mygl"
version = "0.1.0"
authors = ["Michael Fairley <michaelfairley@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "*"

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
debug = true
codegen-units = 32
